### ISSUE TITLE
Brainstorming Ideas For Experience System

### ISSUE THREAD

**Issue by Cooksey99** [humanetes-com/proof-of-positive-interaction#17]
### Initial Problem
How do we determine the amount of experience that a user should be granted per task? 

### Potential Issues
- Abuse of bots
- Falsifying work/task (creating tasks without real work)
- Not everyone will consider the same task to be as difficult, therefore, creating issues with how much experience to be given.

### Possible solutions
- Mentioned by @DeluxeRaph, we could implement a priority system, such as:
  - High priority: 5 exp
  - Medium priority: 3 exp
  - Low priority: 1 exp
  > This would limit the amount of experience that can be given to a task. 
This does **not** solve the problem of someone creating a large amount of tasks or even creating empty, fake, tasks. How do we combat this?
- Each task that's posted to a board requires a fee to be paid
- Possibility of offering paid bounties per task
  - Could offer higher priority options (higher exp), only on paid bounties. 

---
Feel free to help brainstorm ideas on how to solve this problem. Let this be an open discussion.

**Comment by virgiliolino** [comment]
I like the suggestion of investing a fee per task. 
I tried to develop the concept in a document you'll find at the end of this comment. 
Whenever a PO creates a task, blocks some tokens. This task will be moved to the different states from NEW, TO DO, until DONE. Every person who contributed to moving the task from one STATE to the next one, will have a portion of those resources.

Document with the example of a KANBAN Board, with the different COLUMNS, correspondign to STATES and ROLES, constraints and tokenomics: https://docs.google.com/spreadsheets/d/1CsUVA0xI8gknwYteyuK1uXWD2e16-fNpHoMh_MuGv2I/edit#gid=0

**Comment by virgiliolino** [comment]
I found interesting this article:
https://www.nngroup.com/articles/skill-mapping/
