### ISSUE TITLE
How to uniquely identify an Interaction(should we add orgs?)

### ISSUE THREAD

**Issue by virgiliolino** [humanetes-com/proof-of-positive-interaction#24]
As you my see in the pull request:https://github.com/humanetes-com/proof-of-positive-interaction/pull/23
an  interaction is identified univoquely by (approver, worker, project_id, task_id, src_state, dst_state)

where 
* "approver" is another account that is not the worker that is verifying the transition(for example the approval of a  pull request)
* worker is the person who worked on something, for example the creation of a pull request.
* then we have a project id and task id and here it comes the question:
* 
two days ago @Cooksey99 suggested to implement the functionality to register an org. At the beginning it looked a bit far away from the current situation, but now it starts to make sense.

**Comment by Cooksey99** [comment]
Do you mean "uniquely" or "unequivocally"?

I don't have any issues with the way you built it out. It seems to make sense, as far as I can tell.

**Comment by virgiliolino** [comment]
you know my english :) thanks for the correction. I mean uniquely.
Thanks, in the draft I pushed there is an org_id. We must define that structure, as I'm just hardcoding this values.
